### ISSUE TITLE
Hi, I'm new to this... are the Tools Mode in start actually working?

### ISSUE THREAD

**Issue by hendevx** [BOTRaiquia/dota2buttemplate_fixed#12]
I don't see any tutorial, the readme doesn't mention it at all. I thought when I modify some fields, it automates the modification in the files in '\addon_template_butt\scripts or creates a modified 'something-something'. When I enter after inputting a new value, the LOCK + START button turns to red "YOU NEED TO RELOAD!" And I thought about the word reload, do I run the map again? Didn't work. Do I exit the whole workshop tools and open the whole thing again? Didn't work. Hammer > File > Reload From Disk doesn't help as well. I also constantly check if there's some changes in the .txt files in the '\scripts\npc and files in the '\scripts\vscripts. I don't know what to do with it. I thought it was simple as that—or did I miss something and I'm really dumb. lol
What are the Tools Mode for (in the game start)? Thank you.

**Comment by Snoresville** [comment]
I have no idea why this is happening
